### ISSUE TITLE
emitterProperty with component ViewModel doesn't work

### ISSUE THREAD

**Issue by cherifGsoul** [canjs/can-kefir#21]
`Kefir.emitterProperty()` as a value for a ViewModel doesn’t work with `<input on:input:value:to="this.foo.value">`

This [CodePen](https://codepen.io/cherifGsoul/pen/JzLpze) demonstrate thes issue, when you fill the input you should see an error `Uncaught TypeError: Cannot add property value, object is not extensible`.

It seems that a `@@can.hasKey` symbol is needed in the emitterProperty object.

**Comment by chasenlehara** [comment]
Was this fixed?

**Comment by cherifGsoul** [comment]
@chasenlehara yes

**Comment by cherifGsoul** [comment]
Fixed and released https://github.com/canjs/can-kefir/releases/tag/v1.1.3
